### ISSUE TITLE
Add support for unicode fonts

### ISSUE THREAD

**Issue by BNNorman** [BNNorman/rpi-rgb-led-matrix-animator#10]
Currently the code does not support characters beyond ascii code 255.
Need to find out how to put unicode characters into python 2 strings

**Comment by ValDY69** [comment]
Hello Brian ,  did you have time to look at this feature ?

did you have any news ?

**Comment by BNNorman** [comment]
Yes, you can't do it with openCV fonts unless you compile openCV with Qt support (No I don't know the flags but that's not a limitation of my code).

To access the BDF fonts beyond #255 you need to do two things

First, put this at the start of your main.py

\# -\*- coding: UTF-8 -\*-

Then you can declare strings like this (note Euro symbol):-

myString=u"Some message with unicode characters in it like this:- €"

You can paste unicode characters into strings using Windows charmap app.

That's as far as I got with it.

It may be easier to do the work on TrueType and OpenType to offer alternatives to Hershey but I've been tied up with another project for a while.

**Comment by ValDY69** [comment]
ok brian it works for me with BDF
 if we can use TrueType and OpenType fonts , the Hershey isn't important anymore i am agree with you.

what we should do to add this on your work ? 
how we can add TrueType and OpenType support on your library ? 
i can help you i guess but i actually don't know how ...

**Comment by BNNorman** [comment]
I had started work on it but put the brakes on for the project I'm working on.

Firstly, it has to have a unified interface - which might mean re-writing Fonts.py to recognise fonts with bdf, ttf and otf file extensions and routing to relevant Font.py flavours accordingly. Hershey fonts are selected by integer constant values.

Secondly, it needs a TrueType.Fonts.py and OpenType.Fonts.py which use the same calls as BDF.Fonts.py and OPENCV.Fonts.py. I hadn't planned to go that far originally so a re-write might break other font stuff but it would be worth it.

Thirdly, it will use the PIL library to load and render the fonts. Unfortunately PIL uses RGB images and openCV (simulator) uses BGR images. The Panels use RGB so it's a headache making sure colours are always correct when you view in the simulator or the real panel.

Finally, I haven't experimented with PIL but the code looks easy enough BUT it needs to handle transparency, so I need to check that it will work.

So, sounds simple, but a lot of coding and testing.

**Comment by ValDY69** [comment]
Ok Brian i understand that is many work no problem take your time

I have the problem of wrong color too .. your fonts update Will correct this is a good point 

And can i have your personnal email because i want To help you with some contributions because your work is amaizing and very usefull for me i can help in this way if you want ?

**Comment by BNNorman** [comment]
I appreciate the offer of help - that's what github is for - become a contributor.

I have the TTF and OTF partially working - actually PIL has it's own font format too (pil, which has an associated pbm file). At this time, I can render the text into a text buffer but conversion back to a numpy array to merge with the display buffer has produced an unexpected error (ValueError: cannot reshape array of size 25760 into shape (23,280,3)) which is odd considering the image dimensions are correct)

Probably a simple fix hiding in the closet.

I use Numpy arrays for images because of how powerful and fast the numpy library is.

**Comment by ValDY69** [comment]
Ok Brian nice job but i was speaking about some money contribution because i cant really help you in python dev

**Comment by BNNorman** [comment]
Many thanks but no need. I’m just a retired guy who enjoys the challenges of programming.

 

 

The TrueType/OpenType is sort of working – just an issue with RGB/BGR colors, transparency and anti-aliasing to fix. The anti-aliasing may be part of the free ttf font file I chose, not certain if it can be turned on/off in PIL.

**Comment by ValDY69** [comment]
Ok Brian i understand 
I think it could be nice if you create a Dev branch and Feature branch what do you think about this ?

**Comment by BNNorman** [comment]
I think I understand what you mean but I’ve only ever used Github to create and maintain a master branch on my own – I’ll have to read up more about using Github to manage contributions since I use PyCharm to push commits to the repo and it’s a simple process.

 

In the main I though, as has happened so far, people would suggest new features via the “Issues” and I would try to address them (I raised a couple myself as indicators that I intend to address them).

 

I sort of thought the main additions people might want would be extra animations – since these are just small classes which can be bolted on to the relevant <class>Animations.py file it would be easy enough for them to paste the code and I would look at it/incorporate it in the main branch if it didn’t break anything.

 

Alternatively, people could clone the repo as is and work on a new branch entirely on their own.

 

Anyway, as I said. I need to learn more about using git for version control first.

**Comment by ValDY69** [comment]
ok

**Comment by BNNorman** [comment]
I think this issue can be closed because the code does handle unicode fonts if you add

\# -\*- coding: UTF-8 -\*-

at the very start of your main.py. Then you can declare strings like this (note Euro symbol):-

myString=u"Some message with unicode characters in it like this:- €"

It is important to choose a font which supports the unicode characters you want to use. The code now supports TrueType,OpenType and PIL fonts so your choices should be greater.

If you still want dev/feature branches then please raise as a separate issue for that otherwise we will end up talking cross purposes.
