### ISSUE TITLE
Exception in BDF/Font.py

### ISSUE THREAD

**Issue by ValDY69** [BNNorman/rpi-rgb-led-matrix-animator#12]
hello brian ,

i have an exception when i play an animation : 

![image](https://user-images.githubusercontent.com/34503404/37355348-d2f6817a-26e3-11e8-84fb-84ceb6aaae12.png)

Regards , Valentin

**Comment by BNNorman** [comment]
Damn, something always breaks when stuff gets moved. I’m on it.

**Comment by BNNorman** [comment]
Did you download the corrected UtilLib.py?

 

It was originally channelSwap(self,color) but I corrected it to channelSwap(color)

 

Also, I’ve just corrected an import in BDF.Font.py

 

Download both and give it another try – it works here.

**Comment by ValDY69** [comment]
ok brian now it works
thank you
