### ISSUE TITLE
SyntaxError: non-default argument follows default argument

### ISSUE THREAD

**Issue by jghaanstra** [BNNorman/rpi-rgb-led-matrix-animator#17]
When I try to run PanelDemo.py I get the following error:

```
Doing imports, please wait...
PathSetter.py: Parent folder added to sys.path
Traceback (most recent call last):
  File "PanelDemo.py", line 33, in <module>
    from LEDAnimator.Chain import *
  File "/home/pi/rpi-rgb-led-matrix-animator/LEDAnimator/Chain.py", line 37, in <module>
    import Helpers.AntiAlias as AA
  File "/home/pi/rpi-rgb-led-matrix-animator/LEDAnimator/Helpers/AntiAlias.py", line 42
    def antiAlias(self,method=None,coordList):
SyntaxError: non-default argument follows default argument
```

Any clue? Running PanelCheck.py works just fine.

**Comment by jghaanstra** [comment]
Changing line 42 in `/rpi-rgb-led-matrix-animator/LEDAnimator/Helpers/AntiAlias.py` to `def antiAlias(self,method,coordList):` is a workaround.

**Comment by BNNorman** [comment]
Thanks. I'll fix it later on.

**Comment by BNNorman** [comment]
Ok, I had fixed it before but , somehow, hadn't pushed it. My solution was to add coordlist=None.
Thanks for reminding me to push fixes Doh!.
