### ISSUE TITLE
instructions is not clear !!

### ISSUE THREAD

**Issue by idreamsi** [BNNorman/rpi-rgb-led-matrix-animator#2]
Hi Brian,
I am interested in your library but I do not know how to install and run the examples,
I did not find any installation instructions, It's not even clear how the simulator can be run, please correct the instructions.
Also, I wrote an simulator with **pygame** that has an acceptable speed.
I suggest watching the video below.

https://youtu.be/ptke8YdAqJI

Thanks,

**Comment by BNNorman** [comment]
Are you trying to run on a Pi or Windows?

 

On a Pi you need to install the HZeller drivers first. There are some notes in the README, but you should read his notes too.

 

My code doesn’t require any installation other than to clone the repo into a folder.

 

On the Pi, running my examples is the same as running the HZeller python examples:-

 

cd into Examples then :-

 

sudo python <program>               

 

I will make it clearer in README

 

On windows just python <example program> should work (I run from within PyCharm normally.)

 

Thanks for your observation.

 

Regards

Brian

**Comment by BNNorman** [comment]
BTW – nice animations in your video.

**Comment by idreamsi** [comment]
Thanks for reply,
I have not yet tested the examples on Raspberry Pi, But to run the simulator on Windows, I encountered a problem, I do not know where to start, What file do I need to run the simulator?

**Comment by BNNorman** [comment]
Any one of the examples will kick off the simulator.

 

It’s developed on python 2.7

 

Are you running python from the command line?

 

If so, cd to the Examples folder and type: python <example> where <example> is any of the examples except DAF_Chain_Data.py (it’s a data file)

**Comment by idreamsi** [comment]
Thanks Brian,
