### ISSUE TITLE
Freeze after 20min on Panels

### ISSUE THREAD

**Issue by ValDY69** [BNNorman/rpi-rgb-led-matrix-animator#5]
Hello ,

I am doing some test with your Examples and it's like that the program freeze/stop to run.

The animation is stuck but the Rpi isn't bugged

i have to close and rerun the script to start again the animation

The crash occur every 21min and 17sec (i try many times) on your MixedDemo.py with a 64*64 display

There is no crach on the windows simulator.

Can you reproduce this bug on your system ?

Reagards ,
Valentin

**Comment by BNNorman** [comment]
When I’ve solved the gap problem I’ll look at this. It might be an idea to monitor memory to see if there’s a leak.

 

You might look at this for me 

 

https://www.raspberrypi.org/forums/viewtopic.php?t=22180

 

 

whilst I get on with the gap issue

 

Try to see if memory is being gobbled up over time.

**Comment by BNNorman** [comment]
I will look into the freeze thing on the Pi tomorrow.

 

You could put a print statement in the animation loop in Animator.py to check it’s still doing something when it halts.

**Comment by ValDY69** [comment]
ok i look at the memory and cpu with "top" command and it seems that there is no problem with RAM and cpu is 170% but the max is Number_of_cores * 100% --> so i think this is not the problem

i run the samples from Hzeller python binding to be sure that we have not the same issue 
it run for now without any problem ..

I'll let you know 

Regards , Valentin

**Comment by BNNorman** [comment]
Thanks 170% CPU sounds awful. I’m about to upload the latest code to my Pi and try it.

**Comment by ValDY69** [comment]
ok thank you

it's interesting to know if you have the same problem on your pi 

Regards,
Valentin

**Comment by BNNorman** [comment]
Yep, about 20 minutes in.

 

Something to look forward to tomorrow

**Comment by ValDY69** [comment]
Ok Brian ,

I have no freeze with Samples from Hzeller for 3 Hours

Regards,
Valentin

**Comment by BNNorman** [comment]
The problem lies in the Animator.py run() loop.

 

It’s a timing issue which causes the program to lock up in the final loop waiting for frameInterval to expire. 

 

Probable fix would be to abort the loop if the frameInterval has expired. Will investigate tomorrow.

**Comment by BNNorman** [comment]
It was time.clock() in Animator.py  wrapping over after 20 minutes.  I have uploaded a new version – it’s been running on my Pi 3 for over an hour so far.

 

On the PC using a 64 bit machine with 64 bit python it would also happen but you’d die first.  I guess it’s because Python 2.7 on the Pi is 32 bit.

 

I was using time.clock() for accuracy but time.time() should be accurate enough for frame rates under 500fps (if the animations ever allow that sort of speed). 

 

Thanks for all your testing.

 

Regards

Brian

**Comment by ValDY69** [comment]
ok brian perfect 

i am testing without any freeze for now too , i wait for all day and after i close the issue ok ?

thank you brian !

Regards,
Valentin

**Comment by ValDY69** [comment]
ok i close now because no problem for 1 day !

Thank you brian !

Regards,
Valentin
