### ISSUE TITLE
Problem Sequence

### ISSUE THREAD

**Issue by ValDY69** [BNNorman/rpi-rgb-led-matrix-animator#6]
Hello Brian ,

I try to do a simple Programme animation with only a logo and a 2 texts message.

I want to display my logo on the all screen for 5 seconds , after that i want to play two scrolling text for 8 seconds at the same time and loop again all the sequences (Logo + texts). i want that the text is displayed alone (without any logo)

I try some possibilities to do that (with StartPause and EndPause) but isn't work for me because either the text is over the logo or the logo is over the text and it's not good for me ...

Can you help me please ?

Regards,
Valentin

**Comment by BNNorman** [comment]
Can you attach your code so i can try the same. Does the problem exist on
pc and pi? Or only on one?

**Comment by BNNorman** [comment]
Also, have you tried inserting a Wait animation?

**Comment by ValDY69** [comment]
Yes the problem are on both platform
Yes i try to add a Wait animation.

this is my test code : 

PANEL_PARALLEL=2    # 2 in parallel = 64 leds v
PANEL_ROWS=32       # each sub panel is 32 LED x 32
PANEL_COLS=32       # each sub panel is 32 LED x 32
PANEL_SERIES=2      # 2 in series = 64 leds horertical
GPIO_SLOWDOWN = 2   # gets rid of flickering leds on my Pi3

Panel.init(rows=PANEL_ROWS,cols=PANEL_COLS,chain_length=PANEL_SERIES, parallel=PANEL_PARALLEL,multiplexing=1,gpio_slowdown=GPIO_SLOWDOWN,fps=FPS,
           debug=DEBUG,videoCapture=False,videoName="./TextDemo.avi")

logo=Image(imagePath="../Images/logo.jpg",scaleMode="F",alignMode=("C","C"))

cv2Text="Hello"
hershey=Font(FONT_HERSHEY_SIMPLEX,12)
tLenCV2,h=hershey.getTextBbox(cv2Text)

bdfText="Welcome"
bdf=Font("BDF",12)
tLenBDF,h=bdf.getTextBbox(bdfText)

#------------
bdfmsg=Text(text=bdfText, fontSize=12, fontFace="BDF", fgColor=Palette.MAGENTA)

cv2msg=Text(text=cv2Text,fontSize=12,fontFace=FONT_HERSHEY_SIMPLEX,
                 fgColor=Palette.CYAN)


#-----------
bdfSeq= AnimSequence([
    TextAnimations.MoveTimed (duration=13, startPause=5,speed=0.3, fps=FPS, startPos=(64,5), endPos=(-tLenBDF,5), text=bdfmsg,
                         multiColored=True, Xpos=32,Ypos=32,debug=DEBUG,id="BDFSEQ"),
])


cv2Seq= AnimSequence([
    TextAnimations.MoveTimed (duration=13,  startPause=5,speed=0.3, fps=FPS, startPos=(64,36), endPos=(-tLenCV2,36),
                             multiColored=True,
                         text=cv2msg, debug=DEBUG,id="CV2SEQ"),
])

logoSeq= AnimSequence([
    ImageAnimations.RevealIn (duration=5, speed=1.0, fps=FPS, fgImage=logo, revealFrom="Top"),
    ImageAnimations.Wait(background=(0,0,0,0),duration=8,fps=FPS,Xpos=0,Ypos=0,debug=DEBUG,id="BKGND"),
])

A= Animator(debug=DEBUG,fps=FPS)

A.addAnimation(seq=logoSeq,id="FADEIN",debug=DEBUG)

A.addAnimation(seq=bdfSeq,id="BDFSEQ",debug=DEBUG)
A.addAnimation(seq=cv2Seq,id="CV2SEQ",debug=DEBUG)

try:
    print("Running")
    A.run()
    exit(0)

except Exception as e:

    print ("*** exception:")
    exc_type, exc_value, exc_traceback = sys.exc_info()
    traceback.print_exception(exc_type, exc_value, exc_traceback,limit=10, file=sys.stdout)


Regards ,
Valentin

**Comment by ValDY69** [comment]
It seems that the startPause with MoveTimed Animation is particular , because when i add startPause the text not entierely scroll but this is another problem

**Comment by BNNorman** [comment]
startPause and endPause freeze the current animation to give people time to see the beginning and end of an animation E.G. an image before it dissolves.

 

So, the animation played will last for time=duration-startPause-endPause.

 

 

Your sequence configurations looked like this (the numbers are seconds duration):-

 



 

 

This meant the text started at the same time as the logo.

 

They should have been like this:-

 



 

 

The latter works on my machine.

 

Always good to draw a sequence diagram if you are going to have multiple animations running in parallel so that you get the timing right.

 

 

Regards

**Comment by BNNorman** [comment]
Whoops - pasted images vanished...

Your sequences were

logoSeq  <---LOGO--><---WAIT--->
textSeq   <---------TEXT------------>

you should use :-

logoSeq  <---LOGO--><---WAIT--->
textSeq   <---WAIT---><---TEXT---->

**Comment by ValDY69** [comment]
ok brian i test this but it's better but not working properly : 

this is my code : 

bdfSeq= AnimSequence([
    TextAnimations.Wait(duration=5, fps=FPS, Xpos=0, Ypos=0, debug=DEBUG, id="BKGND",text=Text(text="wait", fontSize=12, fontFace=FONT_HERSHEY_SIMPLEX, fgColor=Palette.CYAN)),
    TextAnimations.MoveTimed (duration=8,speed=0.3, fps=FPS, startPos=(64,5), endPos=(-tLenBDF,5), text=bdfmsg,
                         multiColored=True, Xpos=32,Ypos=32,debug=DEBUG,id="BDFSEQ"),

])


cv2Seq= AnimSequence([
    TextAnimations.Wait(duration=5,fps=FPS,Xpos=0,Ypos=0,debug=DEBUG,id="BKGND",text=Text(text="wait",fontSize=12,fontFace=FONT_HERSHEY_SIMPLEX,fgColor=Palette.CYAN)),
    TextAnimations.MoveTimed (duration=8,speed=0.3, fps=FPS, startPos=(64,36), endPos=(-tLenCV2,36),
                             multiColored=True,
                         text=cv2msg, debug=DEBUG,id="CV2SEQ"),
])

i send you only the two modified text seq

i have now the text scrolling good but the logo isn't displayed properly there is a black rectangle at the top of the logo at the same position at the text ...

**Comment by BNNorman** [comment]
Why have you put the Text() into the Wait? It should have nothing in it as it is just waiting.

 

This is what you should have:-

 

bdfSeq= AnimSequence([
ImageAnimations.Wait(background=(0,0,0,0),duration=5,fps=FPS,Xpos=0,Ypos=0,debug=DEBUG,id="BKGND"),
TextAnimations.MoveTimed (duration=8,speed=0.3, fps=FPS, startPos=(64,5), endPos=(-tLenBDF,5), text=bdfmsg,
multiColored=True, Xpos=32,Ypos=32,debug=DEBUG,id="BDFSEQ"),
])
cv2Seq= AnimSequence([
ImageAnimations.Wait(background=(0,0,0,0),duration=5,fps=FPS,Xpos=0,Ypos=0,debug=DEBUG,id="BKGND"),
TextAnimations.MoveTimed (duration=8,speed=0.3, fps=FPS, startPos=(64,36), endPos=(-tLenCV2,36),
multiColored=True,
text=cv2msg, debug=DEBUG,id="CV2SEQ"),
])

**Comment by ValDY69** [comment]
ok it works with the ImageAnimation.wait instead of the textAnimation.wait

Thank you

**Comment by BNNorman** [comment]
Ok,

 

Probably because the ImageAnimation base object ImageAnimBase() doesn’t process the Text() object (It isn’t expecting one).

 

If you include a Text() object as a parameter to Wait() it creates an empty image to place the text into – that’s where the black rectangle appeared from.

 

Moral – keep it simple J

**Comment by ValDY69** [comment]
ok i understand brian
