### ISSUE TITLE
Stop and Restart the Animator

### ISSUE THREAD

**Issue by ValDY69** [BNNorman/rpi-rgb-led-matrix-animator#8]
Hello Brian ,

I don't find a way to Stop and restart the Animator

like A.stop() to stop the animator on the panel and after add new Sequence and relaunch it for exemple 

Can you help me ?

Regards , 
Valentin

**Comment by BNNorman** [comment]
That’s because it wasn’t designed to work that way.

The Animator.py run() method has a “while True” loop – so it doesn’t return till the Panel is stopped from running and since it runs in the foreground there’s no way to stop it.

So, you need to execute run() in a thread.

Step 1:
Add the import for threading:-

Import threading

Step 2:
Create two new methods:-

def start(self):
	self.Running=True
	T=threading.thread(target=self.run)
	T.start()

def stop(self):
	self.Running=False

Step 3:
Modify the ‘while’ loop line in  run() (currently line 72) to:

while self.Running:
	
That ought to work but I haven’t tested it.

I think your calling program will have to loop so that the whole program doesn’t terminate. As I said – untested.

**Comment by ValDY69** [comment]
ok brian thank you i will test it soon !

**Comment by angelogoncalve** [comment]
Dear Brian and Valentin gives me this error in UtilLib.py. How can fix please? Thank you for your help my friends. The stop and restart the Animator is doing A.stop and A.start correct my friends?

Instead using a boolean variable to start and stop the thread that works fine also, you can use the threading.Event() (also is a boolean variable for threads) and set the event to stop the thread when is need.

C:\Python27\python.exe C:/Users/User/Desktop/rpi-rgb-led-matrix-animator/Examples/txrt.py
cwd= C:\Users\User\Desktop\rpi-rgb-led-matrix-animator\Examples
Starting, please wait...
PathSetter.py: Parent folder [ C:\Users\User\Desktop\rpi-rgb-led-matrix-animator ] already exists in sys.path
Running on Windows simulator
Panel.init() starting..
RGBMatrix: Not recording video
RGBMatrix.run() starting the simulator window.
RGBMatrix.run() entering the run loop frameDuration=33.00ms
 Panel.init() creating frameBuffer width 64,height 64

Running
C:\Users\User\Desktop\rpi-rgb-led-matrix-animator\LEDAnimator\UtilLib.py:65: RuntimeWarning: invalid value encountered in divide
+ dst_rgb * dst_a[..., None] * (1.0 - src_a[..., None])) / out_a[..., None]
Animator.run() Animation frame interval exceeded - check animation durations. Total loopTime= 0.0390000343323 frameInterval= 0.0333333333333

**Comment by BNNorman** [comment]
Read the beginning of UtilLib.py. This is a numpy warning. It should not cause the program to halt.

**Comment by BNNorman** [comment]
A.stop() and A.start() would be the correct way.

**Comment by ValDY69** [comment]
ok brian it's working with thread but the only problem for me is that the A.stop don't clear the screen : 

it's like a "pause" but when i restart it again (A.start) it's run from begining 

there is a way for the stop to clear the screen to have a black screen on my led Panels ?

Thank you brian

Reagards ,
Valentin

**Comment by BNNorman** [comment]
Try putting Panel.clear() inside the stop() method.

Sent from my Fire

On 21 February 2018, at 08:33, ValDY69 <notifications@github.com> wrote:

ok brian it's working with thread but the only problem for me is that the A.stop don't clear the screen :

it's like a "pause" but when i restart it again (A.start) it's run from begining

there is a way for the stop to clear the screen to have a black screen on my led Panels ?

Thank you brian

Reagards ,
Valentin

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/BNNorman/rpi-rgb-led-matrix-animator","title":"BNNorman/rpi-rgb-led-matrix-animator","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/BNNorman/rpi-rgb-led-matrix-animator">https://github.com/BNNorman/rpi-rgb-led-matrix-animator</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ValDY69 in #8: ok brian it's working with thread but the only problem for me is that the A.stop don't clear the screen : \r\n\r\nit's like a \"pause\" but when i restart it again (A.start) it's run from begining \r\n\r\nthere is a way for the stop to clear the screen to have a black screen on my led Panels ?\r\n\r\nThank you brian\r\n\r\nReagards ,\r\nValentin "}],"action":{"name":"View Issue","url":"<a href="https://github.com/BNNorman/rpi-rgb-led-matrix-animator/issues/8#issuecomment-367250070">https://github.com/BNNorman/rpi-rgb-led-matrix-animator/issues/8#issuecomment-367250070</a>"}}}

**Comment by ValDY69** [comment]
i try it , but it's not working : Panel.Clear() do nothing for me

**Comment by BNNorman** [comment]
run() is now in a background thread - it may not terminate immediately but your code would execute before it does.
You could put a Panel.Clear() at the end of run() in Animator.py - that should then execute when the thread starts to exit. OR put a short delay in your Stop() before you call Panel.Clear().

**Comment by ValDY69** [comment]
i try to add Panel.Clear() at the end of run() but it's the same not working 

i try to put a time.sleep() before call Panel.Clear() in Stop() but not working too

**Comment by angelogoncalve** [comment]
Use this and tell me if ti works please. Thanks Dear friend Valentin.

#!/usr/bin/env python
"""
Animator.py

Class to add animation sequences to a list and cycle through them at a pace determined by
the fps of the animation.

If the Panel exits this code will halt

"""
import time
from AnimInfo import AnimInfo
import Panel
import threading

class Animator(object):

    chain=None      # updated by addAnimation
    seq=None        # animation sequence
    fps=None        # passed in

    #debugging
    debug=False
    id="[No id]"
    warned=False

    def __init__(self, **kwargs):

        for key,value in kwargs.iteritems():
            setattr(self,key,value)

        self.animations = []
        self.__threads = []

    def addAnimation(self, **kwargs):

        self.chain=None # text animations don't specify a chain
        self.seq=None

        for key,value in kwargs.iteritems():
            setattr(self,key,value)

        self.animations.append(AnimInfo(chain=self.chain,animSeq=self.seq,fps=self.fps,id=self.id))

    def checkPanelIsRunning(self):
        # simulator window may have been closed
        if Panel.isRunning(): return

        # possibly the Panel is taking time to initialise
        # terminate if timeout reached

        t0 = time.time()
        while not Panel.isRunning():
            if (time.time() - t0) >= 5:
                if self.debug: print "Animator: panel is not running (5s timeout whilst waiting)."
                exit(0)

    def run(self):
        """
        the animation run loop
        :return: Nothing
        """
        assert self.fps is not None,"Animator.run() - fps not set."

        # if fps is integer 1/fps would be integer zero!
        frameInterval=1.0/self.fps

        if self.debug: print "Animator.run() Frame interval=",frameInterval

        avg_frametime=0

        warned=False

        while self.Running:
        #while True:

            # simulator window may have been closed
            # this exits if so
            self.checkPanelIsRunning()

            t0 = time.time()    # start time for this frame

            Panel.Clear()

            # run through all the animations.
            # the animation list contains info about each animation
            # We call nextFrame() for each one on each pass
            for animInfo in self.animations:
                if animInfo is None:
                    print "Animator.run() No animation info."
                    exit(1)

                if self.debug:
                    t2=time.time()
                    animInfo.nextFrame(self.debug)
                    t3=time.time()
                    if (t3-t2)>frameInterval:
                        print "Animator.run() anim.nextFrame() took","%.6f" % (t3-t2,) ,"for ",\
                            animInfo.animFunc.__class__.__name__,"frameInterval is",frameInterval
                else:
                    animInfo.nextFrame(self.debug)

            # copy panel frame buffer to actual or simulator matrix

            Panel.UpdateDisplay()

            # work out if we need to wait before the next loop
            loopTime=time.time() - t0

            # check if
            if (loopTime>frameInterval) and not self.warned:
                print "Animator.run() Animation frame interval exceeded - check animation durations. " \
                                     "Total loopTime=",loopTime,"frameInterval=",frameInterval
                self.warned=True

            # slow down animation cycle to match the required frameInterval
            # this gives a repeatable time interval for the animations
            # 200fps may not be achievable.

            if self.debug:
                if avg_frametime==0:
                    avg_frametime=loopTime
                else:
                    avg_frametime=(avg_frametime+loopTime)/2

                print "Animator.run() Frame animations took average of %.6f seconds" % (avg_frametime)

            # wait till the next frame interval
            while loopTime < frameInterval:
                loopTime = time.time() - t0

    def start(self):
        self.__clear_threads()
        self.Running = True
        T = threading.Thread(target=self.run)
        self.__threads.append(T)
        T.start()

    def stop(self):
        self.Running = False
        #self.__threads = []
        #Panel.Clear()

    def __clear_threads(self):
        """
        Cleans Threads
        :return:
        """
        # Request to stop every thread on the list
        for thread in self.__threads:
            #thread.stop()
            thread.join()

        self.__threads = []  # Kills Every matrix thread
        print('Threads stopped')

        Panel.Clear()
        return

**Comment by ValDY69** [comment]
Thank you ! 

i try it but not working i have the following error when try to rerun a A.start() after a first A.stop() : 

*** exception:
Traceback (most recent call last):
  File "D:\rpi-rgb-led-matrix-animator/farled/testLogoandText.py", line 105, in <module>
    A.start()
  File "D:\rpi-rgb-led-matrix-animator\LEDAnimator\Animator.py", line 134, in start
    self.__clear_threads()
  File "D:\rpi-rgb-led-matrix-animator\LEDAnimator\Animator.py", line 152, in __clear_threads
    thread.stop()
AttributeError: 'Thread' object has no attribute 'stop'

**Comment by BNNorman** [comment]
Send me your code.

**Comment by angelogoncalve** [comment]
I run the Animator.py code that I sent you and no gives me any errors Dear Valentin using A.stop() and A.start() in testLogoandText.py. Could you send me your code to see what happens and try to fix the errors? Thank you for your attention my friend.

**Comment by ValDY69** [comment]
yes i use A.start() and A.Stop() in my test Python script 

i have copy/paste your Animator.py it's strange ...

it's my test script code : 


'''
TextDemo.py - Moving text a plus fade

'''

# information only
import os
cwd=os.getcwd()
print "cwd=",cwd

print ("Starting, please wait...")
import PathSetter
import sys
import traceback

from LEDAnimator import TextAnimations,ImageAnimations
from LEDAnimator.Animator import Animator
import LEDAnimator.Panel as Panel
from LEDAnimator.AnimSequence import AnimSequence
from LEDAnimator.Font import *
import LEDAnimator.Palette as Palette
from LEDAnimator.Image import *
from LEDAnimator.Text import *

FPS=30 # frames per sec for the animation
DEBUG=False

if DEBUG:
    sys.stdout=sys.stderr   # unbuffered debug messages

# my panel is 64x64 made up of two panels stacked on top of each otherizontal
PANEL_PARALLEL=2    # 2 in parallel = 64 leds v
# each panel is a single piece but is made of two 32x32 panels side by side
PANEL_ROWS=32       # each sub panel is 32 LED x 32
PANEL_COLS=32       # each sub panel is 32 LED x 32
PANEL_SERIES=2      # 2 in series = 64 leds horertical
GPIO_SLOWDOWN = 2   # gets rid of flickering leds on my Pi3

# The panel must be initialised first
# params LEDspacing and LEDsize control the simulator window size
Panel.init(rows=PANEL_ROWS,cols=PANEL_COLS,chain_length=PANEL_SERIES, parallel=PANEL_PARALLEL,multiplexing=1,gpio_slowdown=GPIO_SLOWDOWN,fps=FPS,
           debug=DEBUG,videoCapture=False,videoName="./TextDemo.avi")

# Images used - not loaded till required
logo=Image(imagePath="../Images/logo.jpg",scaleMode="F",alignMode=("C","C"))

cv2Text="Hello"
hershey=Font(FONT_HERSHEY_SIMPLEX,12)
tLenCV2,h=hershey.getTextBbox(cv2Text)

bdfText="Welcome"
bdf=Font("BDF",12)
tLenBDF,h=bdf.getTextBbox(bdfText)

#------------
bdfmsg=Text(text=bdfText, fontSize=12, fontFace="BDF", fgColor=Palette.MAGENTA)

cv2msg=Text(text=cv2Text,fontSize=12,fontFace=FONT_HERSHEY_SIMPLEX,
                 fgColor=Palette.CYAN)


#-----------
bdfSeq= AnimSequence([
    ImageAnimations.Wait(background=(0, 0, 0, 0), duration=5, fps=FPS, Xpos=0, Ypos=0, debug=DEBUG, id="BKGND"),
    TextAnimations.MoveTimed (duration=8,speed=0.3, fps=FPS, startPos=(64,5), endPos=(-tLenBDF,5), text=bdfmsg,
                         multiColored=True, Xpos=32,Ypos=32,debug=DEBUG,id="BDFSEQ"),

])

cv2Seq= AnimSequence([
    ImageAnimations.Wait(background=(0, 0, 0, 0), duration=5, fps=FPS, Xpos=0, Ypos=0, debug=DEBUG, id="BKGND"),
    TextAnimations.MoveTimed (duration=8,speed=0.3, fps=FPS, startPos=(64,36), endPos=(-tLenCV2,36),
                             multiColored=True,
                         text=cv2msg, debug=DEBUG,id="CV2SEQ"),
])

logoSeq= AnimSequence([
    ImageAnimations.RevealIn (duration=5, speed=1.0, fps=FPS, fgImage=logo, revealFrom="Top"),
    ImageAnimations.Wait(background=(0,0,0,0),duration=8,fps=FPS,Xpos=0,Ypos=0,debug=DEBUG,id="BKGND"),
])

# create the animator object
A= Animator(debug=DEBUG,fps=FPS)

A.addAnimation(seq=logoSeq,id="FADEIN",debug=DEBUG)

A.addAnimation(seq=bdfSeq,id="BDFSEQ",debug=DEBUG)
A.addAnimation(seq=cv2Seq,id="CV2SEQ",debug=DEBUG)



# run the animation
try:
    print("Running")
    A.start()

    time.sleep(10)

    A.stop()


    time.sleep(10)

    A.start()
    #A.run()
    exit(0)

except Exception as e:

    print ("*** exception:")
    exc_type, exc_value, exc_traceback = sys.exc_info()
    traceback.print_exception(exc_type, exc_value, exc_traceback,limit=10, file=sys.stdout)

**Comment by angelogoncalve** [comment]
Use this Dear friend Valentin. Tell me if works like you want my friend. Thanks for your help.

def __clear_threads(self):
    """
    Cleans Threads
    :return:
    """
    # Request to stop every thread on the list
    for thread in self.__threads:
        #thread.stop()
        thread.join()

    self.__threads = []  # Kills Every matrix thread
    print('Threads stopped')

    Panel.Clear()
    return

**Comment by ValDY69** [comment]
i have no more error now but the same problem that the A.stop() it's like a pause and not return to black screen

**Comment by angelogoncalve** [comment]
I will try tomorrow another way using Threading.Event boolean flag and put the Animator.py as a class thread but with join() in thread works but not clean the panel...

#!/usr/bin/env python
"""
Animator.py

Class to add animation sequences to a list and cycle through them at a pace determined by
the fps of the animation.

If the Panel exits this code will halt

"""
import time
from AnimInfo import AnimInfo
import Panel
import threading

class Animator(object):

    chain=None      # updated by addAnimation
    seq=None        # animation sequence
    fps=None        # passed in

    #debugging
    debug=False
    id="[No id]"
    warned=False

    def __init__(self, **kwargs):

        for key,value in kwargs.iteritems():
            setattr(self,key,value)

        self.animations = []
        self.__threads = []

    def addAnimation(self, **kwargs):

        self.chain=None # text animations don't specify a chain
        self.seq=None

        for key,value in kwargs.iteritems():
            setattr(self,key,value)

        self.animations.append(AnimInfo(chain=self.chain,animSeq=self.seq,fps=self.fps,id=self.id))

    def checkPanelIsRunning(self):
        # simulator window may have been closed
        if Panel.isRunning(): return

        # possibly the Panel is taking time to initialise
        # terminate if timeout reached

        t0 = time.time()
        while not Panel.isRunning():
            if (time.time() - t0) >= 5:
                if self.debug: print "Animator: panel is not running (5s timeout whilst waiting)."
                exit(0)

    def run(self):
        """
        the animation run loop
        :return: Nothing
        """
        assert self.fps is not None,"Animator.run() - fps not set."

        # if fps is integer 1/fps would be integer zero!
        frameInterval=1.0/self.fps

        if self.debug: print "Animator.run() Frame interval=",frameInterval

        avg_frametime=0

        warned=False

        while self.Running:
        #while True:

            # simulator window may have been closed
            # this exits if so
            self.checkPanelIsRunning()

            t0 = time.time()    # start time for this frame

            Panel.Clear()

            # run through all the animations.
            # the animation list contains info about each animation
            # We call nextFrame() for each one on each pass
            for animInfo in self.animations:
                if animInfo is None:
                    print "Animator.run() No animation info."
                    exit(1)

                if self.debug:
                    t2=time.time()
                    animInfo.nextFrame(self.debug)
                    t3=time.time()
                    if (t3-t2)>frameInterval:
                        print "Animator.run() anim.nextFrame() took","%.6f" % (t3-t2,) ,"for ",\
                            animInfo.animFunc.__class__.__name__,"frameInterval is",frameInterval
                else:
                    animInfo.nextFrame(self.debug)

            # copy panel frame buffer to actual or simulator matrix

            Panel.UpdateDisplay()

            # work out if we need to wait before the next loop
            loopTime=time.time() - t0

            # check if
            if (loopTime>frameInterval) and not self.warned:
                print "Animator.run() Animation frame interval exceeded - check animation durations. " \
                                     "Total loopTime=",loopTime,"frameInterval=",frameInterval
                self.warned=True

            # slow down animation cycle to match the required frameInterval
            # this gives a repeatable time interval for the animations
            # 200fps may not be achievable.

            if self.debug:
                if avg_frametime==0:
                    avg_frametime=loopTime
                else:
                    avg_frametime=(avg_frametime+loopTime)/2

                print "Animator.run() Frame animations took average of %.6f seconds" % (avg_frametime)

            # wait till the next frame interval
            while loopTime < frameInterval:
                loopTime = time.time() - t0

    def start(self):
        self.__clear_threads()
        self.Running = True
        self.T = threading.Thread(target=self.run)
        self.__threads.append(self.T)
        self.T.start()

    def stop(self):
        self.Running = False
        #self.__threads = []
        #Panel.Clear()

    def join(self, timeout=None):
        """
        Set Thread flag to stop ->True
        :param timeout: (Optional - Default is None)
        :return:
        """
        self.stop()  # ->True
        #threading.Thread.join(timeout)
        self.T.join(timeout)
        return

    def __clear_threads(self):
        """
        Cleans Threads
        :return:
        """
        # Request to stop every thread on the list
        for thread in self.__threads:
            thread.join()

        self.__threads = []  # Kills Every matrix thread
        print('Threads stopped')

        Panel.Clear()
        return

**Comment by angelogoncalve** [comment]
Correct Dear Valentin you are correct my friend I will use another way tomorrow that I have and I will adapt to see what happens in the simulator and if it works when I call the A.stop(), if the thread stop and clear also the panel. Thank you for your attention Dear friend.

**Comment by BNNorman** [comment]
Apologies: You need to call Panel.UpdateDisplay() after Panel.Clear() - if you read through the run() method of Animator.py you will see that my code does Panel.Clear() - then iterates the list of animations - then Panel.UpdateDisplay() to put the result on the panel.

Don't get too fancy with threads - setting self.running=False should cause your thread to terminate normally - you certainly don't want to kill the simulator thread (doesn't exist on the Pi and real matrix).

**Comment by BNNorman** [comment]
I have updated Animator.py - if you look at my changes you'll see how simple the solution is (No fancy footwork with threads). I also added a new example ThreadedMixedDemos.py which shows the blanked display after Stop() is called.

**Comment by ValDY69** [comment]
Ok thank you Brian, i Will test it as soon as possible

**Comment by ValDY69** [comment]
ok it's exactly what i whant thank you brian ,
i close this issue

Regards,
Valentin
